apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: outline
  namespace: outline
spec:
  entryPoints:
    - web
  routes:
    - match: host(`note.loutik.fr`)
      kind: Rule
      services:
        - name: outline
          port: 3000